
extern float Input0[];
extern float Input1[];
extern float Input2[];
extern float Input3[];
extern float Input4[];
extern float Input5[];
extern float Input6[];
extern float Input7[];
extern float Input8[];
extern float Input9[];
extern float Input10[];
extern float Input11[];
extern float Input12[];
extern float Input13[];
extern float Input14[];
extern float Input15[];
extern float Input16[];
extern float Input17[];
extern float Input18[];
extern float Input19[];
extern float Input20[];
extern float Input21[];

extern float result_mean[6];
extern int result_channel[6];
extern float outarray[100];
extern float thingout[16];
extern int volume;
